### ISSUE TITLE
Unnecessary and duplicate repository configuration in build.gradle

### ISSUE THREAD

**Issue by wilkinsona** [spring-guides/gs-accessing-data-gorm-mongodb#5]
In `build.gradle`, both for the build script's repositories and the main repositories, `mavenLocal()` and `mavenCentral()` are configured twice. Also, the configuration of the `repo.spring.io` repositories is unnecessary as all dependencies are available from Maven central. This is all the configuration that's required:

```
repositories {
    mavenCentral()
}
```

**Comment by gregturn** [comment]
I tried removing [this](https://github.com/spring-guides/gs-accessing-data-gorm-mongodb/blob/master/complete/build.gradle#L2-L4) from build.gradle, but then it said it couldn't find the spring-boot-gradle-plugin.

I have sifted through the guides and ripped out repo.spring.io as well as mavenLocal.
